apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: aiops-idp-backstage/aiops-modules/modules/sagemaker/sagemaker-custom-kernel
  description: ${{ values.name }} custom kernel template running on AWS sagemaker
spec:
  type: service
  owner: user:guest
  lifecycle: experimental