name: mlops-sagemaker
toolchainRegion: us-east-1
forceDependencyRedeploy: true
groups:
  - name: networking
    path: manifests/mlops-sagemaker/networking-modules.yaml
  - name: sagemaker-studio
    path: manifests/mlops-sagemaker/sagemaker-studio-modules.yaml
  - name: sagemaker-endpoints-module
    path: manifests/mlops-sagemaker/sagemaker-endpoints-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true