name: mlops-sagemaker
toolchainRegion: us-east-1
forceDependencyRedeploy: true
groups:
  - name: networking
    path: manifests/mlops-sagemaker/networking-modules.yaml
  - name: storage
    path: manifests/mlops-sagemaker/storage-modules.yaml
  - name: model-package-promote-pipeline-module
    path: manifests/mlops-sagemaker/sagemaker-model-package-promote-pipeline-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true